image:
  repository: 804054839611.dkr.ecr.eu-central-1.amazonaws.com/ecr-repo-18062025214500
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

config:
  POSTGRES_HOST: django-postgresql
  POSTGRES_PORT: 5432
  POSTGRES_DB: django_db
  POSTGRES_USER: django_user
  POSTGRES_PASSWORD: pass12345

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: pass12345
        username: django_user
        database: django_db
        password: pass12345
  primary:
    persistence:
      size: 2Gi