image:
  repository: 024937406982.dkr.ecr.eu-central-1.amazonaws.com/lesson-5-ecr
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000 # Django gunicorn/uvicorn default if you set it so

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  # (Optionally) targetMemoryUtilizationPercentage: 70

config:
  # Move your Topic 4 env vars here as key: value (non-secret)
  DJANGO_SETTINGS_MODULE: "project.settings"
  DEBUG: "false"
  # DATABASE_URL: "postgres://..."
  # SECRET_KEY should NOT be here if sensitive â†’ put in Secret instead

podAnnotations: {}

nodeSelector: {}
tolerations: []
affinity: {}

container:
  name: django
  port: 8000
  command: []     # e.g. ["gunicorn","project.wsgi:application","-b","0.0.0.0:8000"]
  args: []        # or use args if you prefer

envFromConfigMap: true
