image:
  repository: 024937406982.dkr.ecr.eu-central-1.amazonaws.com/ecr-repo-18062025214500
  tag: v1.0.7
  pullPolicy: IfNotPresent
#  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false
